### ISSUE TITLE
Agrona transport is flushing partial write when unexpected data is read

### ISSUE THREAD

**Issue by cmebarrow** [k3po/k3po#397]
Test case is described in https://github.com/reaktivity/nukleus-tcp.java/issues/7. In that test, the following extract of the script fails because extra data is read before the disconnected event is received:
```
read [0x00 0x00 0x00 0x02]
read ${targetInputId}
read [0x0b] "client data"
read [0x00]

write [0x40 0x00 0x00 0x02]
write ${targetInputId}
write [0x0d 0x00 0x00 0x00]
write flush

close
closed
```
k3po is misbehaving by flushing the first write in this case (depending on timing), so just the first four bytes get flushed (0x40 0x00 0x00 0x02), which is an incomplete message. k3po showed in this case either flush or three writes or none.

**Comment by jfallows** [comment]
This appears to be caused by the implicit flush of pending writes when the `AgronaChannel` is [closed](https://github.com/k3po/k3po/blob/develop/driver/src/main/java/org/kaazing/k3po/driver/internal/netty/bootstrap/agrona/AgronaWorker.java#L262).

While this behavior seems correct for the normal close scenario, it leads to flushing incomplete messages for the Agrona transport when the channel is closed [during cleanup](https://github.com/k3po/k3po/blob/develop/driver/src/main/java/org/kaazing/k3po/driver/internal/Robot.java#L547) at the end of a test failure.

One possible fix would be to remove the flush-on-close behavior from the Agrona transport, and instead automatically inject `write flush` before `close` when the script is parsed.

**Comment by cmebarrow** [comment]
@jfallows I have confirmed this fix resolves the issue.
