### ISSUE TITLE
Regresssion:  k3po-maven-plugin stop is taking ages, over 1 minute

### ISSUE THREAD

**Issue by cmebarrow** [k3po/k3po#400]
This happens when I upgrade from k3po 3.0.0-alpha-54 to 3.0.0-alpha-61. Note that John who it is not caused by his fix for https://github.com/k3po/k3po/issues/397.

To reproduce:
- checkout https://github.com/reaktivity/nukleus.spec.git
- build, observe it takes about 10secs (on my Winodws 10 laptop at any rate)
- edit pom.xml to change k3po version from k3po 3.0.0-alpha-54 to 3.0.0-alpha-61
- rebuild and observe it pauses for a long time (about 30 secs) in k3po-maven-plugin stop

Thread dump:
[threads.txt](https://github.com/k3po/k3po/files/759536/threads.txt)

The regression is not observed using 3.0.0-alpha-60, so it happened between that and 61.

**Comment by dpwspoon** [comment]
I ran with mvnDebug, while running k3po tests.  It appears that controlHandlers in  org.kaazing.k3po.driver.internal.RobotServer is growing per a test, and then waiting to close in the loop

RobotServer#stop()
```java
        for (ControlServerHandler controller : controlHandlers) {
            controller.getChannelClosedFuture().awaitUninterruptibly(2000);
            // controller.completeShutDown(2000);
        }
```

**Comment by StCostea** [comment]
There was an issue with trying to re-initialize a driver after the script ended. We initially decided that after a DISPOSE we can reuse the same connection to the driver for another test. As part of this re-initialization, I was resetting the channelClosedFuture. I think that this messed up the clean-up part on closing the connection.

I have removed that part of the code. The additional effect now is that the driver will not be available for another test on the same connection after the first one finished. 
As discussed with David previously for error cases (to end the connection), I think we can change also the specs in order to have only one test per connection and to close the connection on error and on dispose.

I will do a PR with the fix for current issue. We can do the other change later.

**Comment by StCostea** [comment]
PR: https://github.com/k3po/k3po/pull/401
